title: Bunnix
description: Ultra-lightweight reactive UI framework
theme: jekyll-theme-minimal
url: https://bunnix-js.github.io/bunnix
baseurl: /bunnix
markdown: kramdown
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /bunnix/
  - title: GitHub
    url: https://github.com/bunnix-js/bunnix
